# Generated by Django 2.2.12 on 2020-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollarBought', models.CharField(max_length=60)),
                ('dollarSold', models.CharField(max_length=60)),
            ],
        ),
    ]
